// Generated by scripts/module-counts.mjs — do not edit by hand.
// Run `npm run module-counts` after adding or removing a chapter.
import type { StageId } from "./types";

/** Chapters per world, all four kinds counted. */
export const MODULE_COUNTS: Record<StageId, number> = {
  lagstadiet: 51,
  mellanstadiet: 48,
  hogstadiet: 40,
  gymnasiet: 30,
};
