/**
 * Writes src/lib/moduleCounts.ts — how many chapters each world holds.
 *
 * The start page wants to say "12 av 51 kapitel klara", but the four
 * content.json files are 2.6 MB together and it has no other reason to load
 * them. These are four numbers, so they are baked in instead. validate-content
 * fails if they drift out of step with the content.
 */
import { readFileSync, writeFileSync } from "node:fs";

const STAGES = ["lagstadiet", "mellanstadiet", "hogstadiet", "gymnasiet"];
const KINDS = ["grammar", "spelling", "wordsearch", "stavningstest"];

export function countModules() {
  const counts = {};
  for (const stage of STAGES) {
    const data = JSON.parse(readFileSync(`public/content/${stage}/content.json`, "utf8"));
    counts[stage] = KINDS.reduce((n, k) => n + (data[k] ?? []).length, 0);
  }
  return counts;
}

export function render(counts) {
  const body = STAGES.map((s) => `  ${s}: ${counts[s]},`).join("\n");
  return `// Generated by scripts/module-counts.mjs — do not edit by hand.\n`
    + `// Run \`npm run module-counts\` after adding or removing a chapter.\n`
    + `import type { StageId } from "./types";\n\n`
    + `/** Chapters per world, all four kinds counted. */\n`
    + `export const MODULE_COUNTS: Record<StageId, number> = {\n${body}\n};\n`;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const counts = countModules();
  writeFileSync("src/lib/moduleCounts.ts", render(counts));
  console.log("src/lib/moduleCounts.ts skriven:", JSON.stringify(counts));
}
